export const actionsTypes = {
    FILTER_COUNTRIES: "FILTER_COUNTRIES",
    GET_COUNTRIES: "GET_COUNTRIES",
    SET_PAGINA_ACTUAL: "SET_PAGINA_ACTUAL",
    ORDER_BY_NAME: "ORDER_BY_NAME",
    GET_SEASONS: "GET_SEASONS",
    GET_DIFFICULTY: "GET_DIFFICULTY",
    SEARCH_COUNTRIES: "SEARCH_COUNTRIES",
    POST_ACTTIVITY: "POST_ACTTIVITY",
    GET_DETAIL_ACTIVITY: "GET_DETAIL_ACTIVITY",
}